### ISSUE TITLE
How to decode account data into custom object?

### ISSUE THREAD

**Issue by nukec** [bmresearch/Solnet#140]
Seems that I cant find an example for that. I'm using base64.

**Comment by murlokito** [comment]
This depends on the kind of object you're trying to decode but here's a general idea of what to do to try and decode the data:

First and foremost decode the data from base64 into a `byte[]` a `Span<byte>` or whatever your preferred type for this is going to be, you can check some examples of this being done in the Serum code [here](https://github.com/bmresearch/Solnet.Serum/blob/master/Solnet.Serum/SerumClient.cs#L123) (note: this code is still under development and subject to changes)

Afterwards, it depends on the type of account you're trying to decode, certain accounts will have a certain data layout, i.e. Serum Market accounts have a certain layout (i.e. [Serum Market account layouts](https://github.com/bmresearch/Solnet.Serum/blob/master/Solnet.Serum/Layouts/MarketDataLayout.cs)), and they have to be decoded according to that layout, by using offsets and reading the desired data type at that layout, as you can see by the static `Deserialize` method on the `Market` class [here](https://github.com/bmresearch/Solnet.Serum/blob/master/Solnet.Serum/Models/Market.cs#L121).

Does this answer your question?

**Comment by murlokito** [comment]
To add more context to this, the latest v0.3.1 release features additions of utility methods that can be used to make encoding and decoding of program and account data much easier, the implementations of SPL and Native programs inside `Solnet.Programs` have already been refactored to use these methods, while the refactoring of `Solnet.Serum` to use these same methods is underway. You can check those methods here:

[Encoding](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Programs/Utilities/Serialization.cs)
[Decoding](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Programs/Utilities/Deserialization.cs)

They should make the program and account data encoding and decoding much cleaner and easy to implement, they are also open to additions :)

**Comment by nukec** [comment]
thanks that helped
