### ISSUE TITLE
Change TokenBalance Amount type from string to ulong

### ISSUE THREAD

**Issue by aph5nt** [bmresearch/Solnet#156]
Is it a good idea to change public string Amount { get; set; } into ulong (there is UiAmountString already if someone will need string)? Now I have to parse a string into ulong in my code. 

    /// <summary>
    /// Represents the token balance of an account.
    /// </summary>
    public class TokenBalance
    {
        /// <summary>
        /// The raw token account balance without decimals.
        /// </summary>
        public string Amount { get; set; }

        /// <summary>
        /// The number of base 10 digits to the right of the decimal place.
        /// </summary>
        public int Decimals { get; set; }

        /// <summary>
        /// The token account balance, using mint-prescribed decimals. DEPRECATED.
        /// </summary>
        [Obsolete("UiAmount is deprecated, please use UiAmountString instead.")]
        public decimal? UiAmount { get; set; }

        /// <summary>
        /// The token account balance as a string, using mint-prescribed decimals.
        /// </summary>
        public string UiAmountString { get; set; }
    }

**Comment by murlokito** [comment]
I'm not exactly sure of this but I think they are coming back formatted as an actual `string` so this would need a converter to be possible.

See: https://docs.solana.com/developing/clients/jsonrpc-api#token-balances-structure

I'm gonna dig into this

**Comment by murlokito** [comment]
I think we could do something like adding two new properties, one for `Amount` that would convert it to ulong and another for `UiAmountString` to return it as either float or double. This way you wouldn't need to be fiddling around with more Json Converters etc. since these are values that are going to be needed a lot in wallet/tx contexts

 It's just the naming of those new properties that would be tricky, idk if the following examples would be too verbose or not:

```
public ulong AmountUlong => Convert.ToUint64(Amount);
public double AmountUlong => Convert.ToDouble(UiAmountString);
```

**Comment by murlokito** [comment]
Following up on this @aph5nt, I've checked in with @tiago18c and if you're down to implement these additions we're good with adding the following properties to this class in order to makes things easier and not have too much work with Converters while also keeping API fidelity high.

```
public ulong AmountUlong => Convert.ToUint64(Amount);
public double AmountDouble => Convert.ToDouble(UiAmountString);
```

**Comment by aph5nt** [comment]
yes, i will do it
