### ISSUE TITLE
Example of sending TOKEN to external account would be helpful.

### ISSUE THREAD

**Issue by aph5nt** [bmresearch/Solnet#158]
Hi guys, 
I'm trying to send the existing token to an external account. So far I have had no issues with transferring it to myself, or to an account that is aware already of the given token. 

The problem is that I don't know how to Initialize an external account, please advise. You can find below the code I was playing with.

``` 
var tx = new TransactionBuilder().
                SetRecentBlockHash(blockHash.Result.Value.Blockhash).
                SetFeePayer(ownerAccount).
                AddInstruction(SystemProgram.CreateAccount(
                    ownerAccount,
                    new Account(string.Empty, message.Address),  // <== here is a problem, I don't know the private key of external address
                    minBalanceForExemptionAcc,
                    SystemProgram.AccountDataSize,
                    TokenProgram.ProgramIdKey)).
                AddInstruction(TokenProgram.InitializeAccount(toTokenAccountPublicKey, new PublicKey(tokenContractAddress), toTokenAccountPublicKey)).
                AddInstruction(TokenProgram.Transfer(
                    fromTokenAccountPublicKey,
                    toTokenAccountPublicKey,
                    lamportsAmount,
                    ownerAccount))
                .Build();
```

**Comment by aph5nt** [comment]
fyi @murlokito

**Comment by murlokito** [comment]
Can you be more specific on how you mean "external account"? 

Is this token account you mention already created? If so you don't need to do a `CreateAccount` instruction.

All you'd need to do is this: 

```
var tx = new TransactionBuilder().
                SetRecentBlockHash(blockHash.Result.Value.Blockhash).
                SetFeePayer(ownerAccount).
                AddInstruction(TokenProgram.Transfer(
                    fromTokenAccountPublicKey,
                    toTokenAccountPublicKey,
                    lamportsAmount,
                    ownerAccount))
                .Build();

```

**Comment by aph5nt** [comment]
in js it would look like that

```
private _createTokenTransaction(data: {
    seeds: string;
    receiver: string;
    amount;
    lasttx: string;
    contractAddress: string;
    api: string;
  }) {
    return new Promise(async (resolve, reject) => {

      const connection = this.createConnection(data);

      const account = this._generateAccount(data.seeds);
      const recipientPublicKey = new solanaWeb3.PublicKey(data.receiver);

      const myMint = new solanaWeb3.PublicKey(data.contractAddress);
      const myToken = new splToken.Token(connection, myMint, splToken.TOKEN_PROGRAM_ID, account);

      const fromTokenAccount = await myToken.getOrCreateAssociatedAccountInfo(account.publicKey);
      const toTokenAccount = await myToken.getOrCreateAssociatedAccountInfo(recipientPublicKey);

      const transaction = new solanaWeb3.Transaction().add(
        splToken.Token.createTransferInstruction(
          splToken.TOKEN_PROGRAM_ID,
          fromTokenAccount.address,
          toTokenAccount.address,
          account.publicKey,
          [],
          data.amount
        )
      );

      connection.sendTransaction(transaction, [account]).then(res => {
        connection.confirmTransaction(res);
      });
    });
  }
```


to be more precise:
```
const toTokenAccount = await myToken.getOrCreateAssociatedAccountInfo(recipientPublicKey);

```

i wonder how do to this part

**Comment by aph5nt** [comment]
> Is this token account you mention already created?

not, its not created, its brand new wallet

**Comment by murlokito** [comment]
Ok so by the js code looks like you want to use Associated Token Accounts (ATAs).

I haven't had much time to play with this but you'll need to create an instruction with the AssociatedTokenAccountProgram to create that account

```
AssociatedTokenAccountProgram.CreateAssociatedTokenAccount(
     fromAccount,
     newAccountOwnerPublicKey,
     tokenMint)
```

`fromAccount` is the account that will be used to fund the ATA
`newAccountOwnerPublicKey` is the public key of the account that will own the ATA (this is done so you can deterministically get the ATA address for anyone as long as you have the public key of the account that owns the ATA and the token mint)
`tokenMint` is what I assume you have as being `new PublicKey(tokenContractAddress)`

If this doesn't work I will have to play around a bit later and see if there are actual issues that need to be fixed and/or may be related to #152 and #153

**Comment by murlokito** [comment]
I'm gonna work on a quick PR to add an example that uses ATAs

**Comment by murlokito** [comment]
Ok so I found out that when I implemented this I forgot to add the example I had used to test it then and also forgot to add an helper function that derives the ATA address and returns it (it's currently being derived in the function that creates the `TransactionInstruction`).

Working on a fix for this because this needs to be included in v0.4 because it was a major oversight from me.

**Comment by murlokito** [comment]
Sorry for taking so long with this, while checking this out I found out some obscure bug in our Program Derived Addresses, I'm opening a PR that fixes this issue, what I mentioned earlier and adds an example that uses ATAs. @aph5nt

**Comment by murlokito** [comment]
I've fixed some bugs related to this and added an example in a new PR, will close this one when that's merged. See #160.
