### ISSUE TITLE
[Bug] GetTokenAccountsByOwner deserialization error with delegatedAmount account edge case

### ISSUE THREAD

**Issue by liquizard** [bmresearch/Solnet#164]
**Describe the bug**
Found a JSON deserialization issue with the rpcClient.GetTokenAccountsByOwner method...
By fluke, a token account has the following data in the parsed->info response... 

                                 "delegatedAmount": {
                                    "amount": "45",
                                    "decimals": 9,
                                    "uiAmount": 4.5e-8,
                                    "uiAmountString": "0.000000045"
                                }

Most accounts usually have:

                                 "delegatedAmount": 12345

The TokenAccountInfoDetails class has DeletedAmount declared as an ulong, so the above structured data is making the serializer go pop.

    public ulong DelegatedAmount { get; set; }

The error is reported as the generic "Unable to parse json.", but the deserializer's innards say: 
    The JSON value could not be converted to System.UInt64. Path: $.result.value[42].account.data.parsed.info.delegatedAmount 

**To Reproduce**

var token_accounts = client.GetTokenAccountsByOwner(account, tokenProgramId:="TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");

Shared the account that fails - don't want to share the pubkey in this issue.

**Expected behavior**
Deserialization should succeed :-)

**Additional context**
Looks as though the account in question may be related to staking in solfarm.

**Comment by murlokito** [comment]
Thanks for bringing this to our attention..
Looks like most accounts don't even have `delegate` or `delegatedAmount` present, it's really an optional duo and when it is present it it's a string, and the same object as `tokenAmount`, respectively.

Fix has been applied and will be included in v0.4.

**Comment by liquizard** [comment]
Nice work @murlokito - thank you for your help with the quick diagnosis and fix.
