### ISSUE TITLE
Allow access to raw request/response JSON via RequestResult<T>

### ISSUE THREAD

**Issue by liquizard** [bmresearch/Solnet#168]
**Is your feature request related to a problem? Please describe.**
This feature request will extend the utility of the solnet lib beyond the intended happy path.
In unexpected situations where JSON serialization fails - rather than leave the dev/user at a dead end, access to the underlying JSON would enable creative workarounds or perhaps more information to be able to resolve or better diagnose an obstacle.
Another benefit would be greater transparency of the RPC chatter back and forth. Whilst this may not be perfectly aligned with the goals of the solnet project - I think some increase in the visibility of what is going on under the hood is beneficial to all parties in a number of different circumstances. Mostly the powerful magic of .Net JSON deserialization is wonderful until you encounter a breakage, and then it can be difficult to troubleshoot - especially in the hidden depths of a third party code.

**Describe the solution you'd like**
Extending the solnet RequestResult<T> class to provide:

        public string RawJsonRequest { get; set; }
        public string RawJsonResponse { get; set; }

**Describe alternatives you've considered**
Lots of diagnosis is already available via the extensive logging already implemented - but this is not optimal for programmatic inspection or when debugging. I think that adding specific fields offers better semantics and creates more opportunities for a developer to investigate and create solutions to their own problems.

Another alternative would be to throw a custom "JSON unmarshalling exception" that includes the req/response bodies as properties of the exception. This would serve in circumstances where there are mismatches between the expected and actual JSON schemas, but would not allow a curious developer from seeing the payloads of healthy RPC interactions.

**Additional context**
Here a screenshot of the properties at work - I found this useful in understanding and investigating #164  

Also the "unable to parse json" error message is slightly misleading as it sent me down the rabbit hole of thinking the JSON was invalid (badly escaped or truncated buffer etc. ) - the JSON was legit, but the problem was it did not match the expected class shape for deserialization. Perhaps this message could be something like: unable to deserialize json to {typename}

![image](https://user-images.githubusercontent.com/87999215/127123866-9fe94d20-778d-44af-a9d2-57508f806857.png)

Happy to submit a PR if you like the idea(s).

**Comment by murlokito** [comment]
As we discussed following up with your report or #164 I really like this proposal, happy to review a PR with these additions anytime 😀

**Comment by murlokito** [comment]
Closed by #169
