### ISSUE TITLE
Make TransactionInstruction construction accessible to non C# languages

### ISSUE THREAD

**Issue by liquizard** [bmresearch/Solnet#174]
**Is your feature request related to a problem? Please describe.**
Some .Net languages like VB.Net do not support init only setters.
This prevents the construction of TransactionInstruction instances.

**Describe the solution you'd like**
A simple workaround to allow the creation of TransactionInstruction via a Create() method.
Suggest a separate Factory class to keep this Create method away from the main way users would interact with this class.
e.g.

    TransactionInstructionFactory.Create(_program_id.KeyBytes(), keys, data)

Pull request incoming.

**Describe alternatives you've considered**
Changing properties etc. - too much impact for what is a minority edge case.

**Comment by murlokito** [comment]
I'm assuming this is for instructions related to programs we haven't implemented yet?

**Comment by liquizard** [comment]
Howdy - yes, I'm reverse engineering Tulip harvest and ran into this issue when creating the a program class in my prototyping.

**Comment by murlokito** [comment]
Alright sounds good to me. I'm wondering if the same issue affects the programs we have already implemented but I'm assuming they work fine?

**Comment by murlokito** [comment]
Also, if you're down to make it something robust and to potentially releasing it on NuGet, we'd be happy to eventually add it to the list of ecosystem libraries in the README. We'd like to have a cool list of program implementations which aren't using Anchor, since in due time we'll have code generation for Anchor based programs :)

**Comment by liquizard** [comment]
The issue does not affect your built-in programs. 
They work fine, as they have their own factory methods, e.g.

        Dim builder As New TransactionBuilder()
        builder.
            SetRecentBlockHash(blockHash.Result.Value.Blockhash).
            SetFeePayer(fromAccount).
            AddInstruction(MemoProgram.NewMemo(fromAccount, "Hello from Sol.Net :)")).
            AddInstruction(SystemProgram.Transfer(fromAccount, toAccount, 100000))

This issue only crops up when implementing anything that needs to create its own TransactionInstruction instances. 

Thanks - would be happy to share.
Got harvest working, still trying to fathom the enumeration of vaults that belong to an account like Step does.
Any pointers would be greatly appreciated :-)

**Comment by murlokito** [comment]
Would need to take a look at the Tulip structures to know for sure, but I'm assuming the "owner" account is referenced somewhere in the structure, in that case I think you can use `GetProgramAccounts` with the Tulip address and filtering by the offset and comparing with the owner's address at that given offset.

Not at home rn but can take a peek later, also feel free to DM me on discord

**Comment by liquizard** [comment]
Thanks - no hurry - off out myself shortly.
Are the data structures opaque blobs? Or is there any way to gleen their fields/types?

**Comment by murlokito** [comment]
Was digging around and looks like they don't have public source nor plans to publicize it for a bit longer, there is a gist with an IDL for their program which leads me to assume that they are using Anchor. In which case you'd probably be better off working on Anchor-based programs client code generation. This is something we've been wanting to do for a while but haven't quite had time to.

Here's the link to the IDL.
https://gist.github.com/therealssj/b693a82468406e2fa6b282727e06b877

**Comment by murlokito** [comment]
Closed by #175
