### ISSUE TITLE
Add TokenWallet + Solnet.Extensions project

### ISSUE THREAD

**Issue by liquizard** [bmresearch/Solnet#176]
**Is your feature request related to a problem? Please describe.**
I'm thinking there is a gap for a higher-level `TokenWallet` construct that is also capable of understanding and navigating the SPL sub-account relationships of a particular on-chain wallet. This would use the primitive Wallet and RPC together to load account information and balances etc. Such an object could be interrogated by a developer to find Associated Token Accounts for a mint and provision an ATA or sub-account if necessary. 

The Solnet.Wallet project provides all the primitive elements required to interact with a wallet and accounts. As this is all based on crypto and maths all this functionality is deterministic.

The Solnet.Rpc project provides all the means of discovering and querying the blockchain to find out the current real world specifics of a particular wallet, its balance, owned SPL token accounts etc.

This TokenWallet behavior is not mathsy deterministic wallet logic as it depends on the RPC and on-chain state. More akin to RPC functionality as it is mockable for testing inline with other RPC tests. But then it is not primitive RPC functionality either - it just makes use of the RPC. 

For example:

    var wallet = TokenWallet.LoadSnapshot(client, publicKey); // discover accounts via getTokenAccountsByOwner
    var ata = wallet.GetAssocatedTokenAccount(tokenAddress); // get account or null if none exist
    if (ata == null) ata = wallet.CreateAssociatedTokenAccount(tokenAddress); // provision ATA
    var balance = wallet.GetConsolidatedBalance(tokenAddress); // sum balanced of all accounfs for SPL token
    ...
    wallet.Refresh();

Looking to the solanaj project for answers, there is a `TokenManager` class that makes use of the RPC that I think is the closest looking animal. It sits in the `solanaj.token` namespace. Their project doesn't seem to have internal project dependency boundaries to contend with like C#. I couldn't find anything that provides a consolidated balance of a particular SPL token for a top-level account. Is this something we would anticipate a developer should be managing themselves as a necessary complexity?

I have the fundamentals of `TokenWallet` and would be happy to contribute this back into Solnet, but where would it belong? Going off the solonaj namespace, the closest I can come up with would be `Solnet.Token` - but this would need to be a new project. or is that overkill?

**Comment by murlokito** [comment]
This is a really nice add and something I'd love to have in Solnet, I've previously done something similar as a wholly different project to manage ATAs in an application. I'm just a bit fuzzy on the namespace, but at the same feels like `Solnet.Token` is probably the best bet.

 I'll think about this some more.

**Comment by murlokito** [comment]
On further thought I think these additions would be better fitting onto a project called `Solnet.Extensions`, they extend the functionality of the SDK with certain further abstractions that come in handy in a number of different situations. This is because, thinking of dependencies for this `TokenWallet`, it's going to end up depending on everything except `Solnet.KeyStore`, which makes sense in the context of `Extensions`.

`Solnet.Extensions` was also something me and @tiago18c had already discussed and we agreed that sooner or later would end up being created for good, small additions to complement "basic" SDK functionality.

**Comment by liquizard** [comment]
OK, `Solnet.Extensions` sounds like a good home for `TokenWallet`

**Comment by murlokito** [comment]
Closed by #176
