### ISSUE TITLE
Rework, redeploy docs and plan new articles

### ISSUE THREAD

**Issue by murlokito** [bmresearch/Solnet#185]
Since v0.4 has been released the [docs](https://blockmountain.io/Solnet/api/Solnet.KeyStore.html) are really outdated, the plan with this is to redeploy them and potentially plan a new series of articles to be released.

The idea behind this new series of articles is to give some input to certain Solana programming model concepts and eventually lead up to using some of the advanced features just enabled by v0.4, like proper multi sigs, SDK interop, etc.

**Comment by tiago18c** [comment]
Closed by #204 .
