### ISSUE TITLE
Implement `AddSignature` on `TransactionBuilder`

### ISSUE THREAD

**Issue by murlokito** [bmresearch/Solnet#192]
In the context of Solnet.Serum we are, once again, avoiding users of the library having to pass in `Account` and/or `Wallet` to classes and relying on trusting the library is doing what it claims to do. Due to this, the current implementation and first official release of Solnet.Serum (v1.0.0) is going to be a bit heavier on performance than we'd like it to be. This is due to a few issues:

- When using the `TransactionBuilder` to craft a transaction and requesting another component to sign it, by using `CompileMessage()` the library user will be forced to decode the message and populating it with the appropriate signature(s) by doing the following:
```
Transaction tx = Transaction.Populate(Message.Deserialize(msgBytes), signatures);
byte[] txBytes = tx.Serialize(); 
```
- `TransactionBuilder` does not have an `AddSignature(byte[] signature)` method which could be used to build the transaction with

Proposed solution is the addition/rework of the following methods:

- `AddSignature(byte[] signature)` adds a signature to an internal list of signatures in the `TransactionBuilder`
- `Serialize()` which would serialize the transaction into wire format by using the signatures added with the previous method
- Reworking the internal logic so that this is completely compatible with the `Build(Account account)` and `Build(IList<Account> accounts)` methods

This would allow for even more flexibility when integrating with external components and APIs while also making this logic much more economic in terms of memory and performance.

RFC @tiago18c @liquizard @skynetcapital

**Comment by liquizard** [comment]
All for adding your suggestions if it fits this or other use cases.

Should all Solnet protocol libraries serve as elaborate transaction builders only and not be capable of submitting transactions themselves?

Will this mean the execution parts are going to be removed from the `Solnet.Serum` internals?

Wondering whether there are ways we could approach this that still allow libraries to construct and execute transactions without being given wallets/accounts.

Could a `PleaseCanYouSignThis?` callback function help here?

**Comment by murlokito** [comment]
To answer your question, all of those have been implemented in `Solnet.Serum`, it does not take in any `Account` or `Wallet`, it performs the functions of 1) streaming data from Serum markets while converting from the raw values into user-friendly values and 2), when provided with the `PublicKey` of an `ownerAccount` and a method which matches the defined delegate represented as `public delegate byte[] RequestSignature(ReadOnlySpan<byte> messageData);`, it will submit orders on behalf of the user.

We've done it this way so that library users do not have to trust that the library is performing what it claims to perform, while at the same time giving users the ability to deploy the full potential of the `InstructionDecoder` previously implemented.

**Comment by liquizard** [comment]
Ah epic work. Sorry, I have misunderstood this issue as a blocker to Serum.
I think I've got it... Your proposal is providing a better way for a library user to interact with a transaction builder when handling the signing of transactions that somebody else has built for them?

**Comment by murlokito** [comment]
No, this is not a blocker to Serum.

In the end this proposal ends up just being a QOL/feature upgrade which has the benefit of adding improved performance when requesting signatures to external components, because you won't have to compile the message, request the signature, and then decode the message and populate a transaction with the decoded message and the relevant signatures You will only need to compile the message, request the signature, and then `AddSignature()` on the same `TransactionBuilder` and then serialize it and it's ready to send.

i.e.

```
byte[] txBytes = new TransactionBuilder()
    .SetRecentBlockHash(blockHash)
    .SetFeePayer(_ownerAccount)
    .AddInstruction(txInstruction)
    .CompileMessage();

byte[] signatureBytes = _requestSignature(txBytes);

Transaction tx = Transaction.Populate(
    Message.Deserialize(txBytes), new List<byte[]> { signatureBytes });
```


vs

```
TransactionBuilder txBuilder = new TransactionBuilder()
    .SetRecentBlockHash(blockHash)
    .SetFeePayer(_ownerAccount)
    .AddInstruction(txInstruction);

byte[] msgBytes = txBuilder.CompileMessage();
byte[] signatureBytes = _requestSignature(msgBytes);

byte[] txBytes = txBuilder.AddSignature(signatureBytes).Serialize();
```

In this last example you do not need to decode a compiled message only to add a signature and end up serializing it again 1 or 2 lines of code later.

**Comment by liquizard** [comment]
Much prefer no. 2 and all for quality of life improvements.
+ extra bonus for imrpovements that remove CPU work too.
++ bonus points for improved readability.

**Comment by kdcz** [comment]
Is this still considered ?
Also, didn't want to open an issue for that but is there a way to donate?
Thank you.
