### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by pepoon** [bmresearch/Solnet#193]
Hello sols, I'm following the 'Hello World' of Solnet, Docs are out of date.
(https://blockmountain.io/Solnet/articles/hello_world.html)
   var tx = new TransactionBuilder()
                .AddInstruction(memoInstruction)
                .SetFeePayer(wallet.Account)
                .SetRecentBlockHash(recentHash.Result.Value.Blockhash)
                .Build(); <--- Requires Signer

**Comment by murlokito** [comment]
Hi, thanks for reporting this. We already know about it as mentioned in #185.

Time looks rare.

**Comment by tiago18c** [comment]
Going to close this as we updated docs today :)
