### ISSUE TITLE
Add Common Interface for RequestResult<T> for Polymorphism

### ISSUE THREAD

**Issue by liquizard** [bmresearch/Solnet#194]
**Is your feature request related to a problem? Please describe.**
Currently there is no assignment compatibility between different flavours of `RequestResult<T>`
This impedes development of common error and logging strategies within applications.

**Describe the solution you'd like**
Implementing a common interface `IRequestResult` that covers the non-T type dependant methods and properties would allow different flavours of `RequestResult<T>` to be passed around as `IRequestResult`

**Alternatives**
Derive a non-generic `RequestResultBase` base class.
This would achieve the same goal.

Happy to create this as a separate PR if you think 0.4.x would benefits from this.

**Comment by liquizard** [comment]
Added PR #195

**Comment by murlokito** [comment]
Love to see it! Well done @liquizard

**Comment by murlokito** [comment]
Closed by #195
