### ISSUE TITLE
help needed, fee payer

### ISSUE THREAD

**Issue by dzovani** [bmresearch/Solnet#206]
Hi 
if fee paye is also send account, my code works,
if fee payers is different account i get this error

Reason	"invalid transaction: index out of bounds"	string

`var blockHash = rpcClient.GetRecentBlockHash();

                    var tx = new TransactionBuilder().
                            SetRecentBlockHash(blockHash.Result.Value.Blockhash).
                            SetFeePayer(centralWallet.Account).
                            AddInstruction(SystemProgram.Transfer(fromWallet.Account, centralWallet.Account, 100000)).
                            Build(fromWallet.Account);`

can u guide me what my code might be missing, thanx

**Comment by murlokito** [comment]
The fee payer must sign the transaction. The error you're getting is because you signed the transaction with one account and not with the fee payer, but the RPC is trying to validate the transaction and doesn't find the necessary signature by the fee payer.
