### ISSUE TITLE
How to get NFT metadata?

### ISSUE THREAD

**Issue by faha-berdiev** [bmresearch/Solnet#225]
`        "accounts": [
            {
                "publicKey": "FMR1zwHNJQUSTZ6MQXFaUdz2QfUqUvjidCyAcG6dh5CD",
                "owner": "GsguXojeGATpZGW8VNfW8qQCBVodbW2qGS8bUEbdGZfv",
                "isAssociatedTokenAccount": true,
                "lamports": 2039280,
                "accountCount": 1,
                "tokenMint": "8vfMHx8sxoqYs5V11e6LbdVFBUFwgEgXL292r3vpSBTT",
                "symbol": "",
                "tokenName": "Unknown 8vfMHx8sxoqYs5V11e6LbdVFBUFwgEgXL292r3vpSBTT",
                "decimalPlaces": 0,
                "quantityDecimal": 1,
                "quantityRaw": 1
            }
        ],
        "count": 1`
That is a response that we geting, and how to get NFT description and properties from metadata?

**Comment by nukec** [comment]
Hm, this is strange?
![image](https://user-images.githubusercontent.com/3589518/136441215-65ac949c-dc0f-4680-bfd9-0ff3bb77f07b.png)

But when you check on explorer it shows correct owner:
https://explorer.solana.com/address/8g3nahwRZwtQqVcdZyTS3weZ2732SHLPV2htJaYMGdcS?cluster=devnet

![image](https://user-images.githubusercontent.com/3589518/136441346-1a79c485-d294-452a-b6c9-d6f0686f49ef.png)

I think I have to find program derived address?

**Comment by nukec** [comment]
thanks. will you also able to add the encoding type for `getAccountInfo` so we can pass `jsonParsed` which could simplify this bit?

**Comment by nukec** [comment]
yes
