### ISSUE TITLE
Allow IRpcClient creation with custom HttpClient

### ISSUE THREAD

**Issue by ctpdzk** [bmresearch/Solnet#230]
**Is your feature request related to a problem? Please describe.**
Current Solana mainnet rate limits are:

> Maximum number of requests per 10 seconds per IP: 100
> Maximum number of requests per 10 seconds per IP for a single RPC: 40
> Maximum concurrent connections per IP: 40
> Maximum connection rate per 10 seconds per IP: 40
> Maximum amount of data per 30 second: 100 MB
(https://docs.solana.com/cluster/rpc-endpoints)

I reach at least one of these limits oftenly.

**Describe the solution you'd like**
I would like to be able to specify my own HttpClient object in the IRpcClient.GetClient function.
This way we could make our own HttpClient with message handlers such as HttpClientHandler/SocketsHttpHandler, that allows us to set a http proxy.

**Comment by Haniamin90** [comment]
can you provide an example usage for a custom with proxy ?

**Comment by Haniamin90** [comment]
```
var proxy = new WebProxy
{
    Address = new Uri("ip:port"),
    BypassProxyOnLocal = false,
    UseDefaultCredentials = true,

    Credentials = new NetworkCredential(
        userName: "user",
        password: "pass")
};

var httpClientHandler = new HttpClientHandler
{
    Proxy = proxy,
};

var client = new HttpClient(handler: httpClientHandler, disposeHandler: true);


var rpcClient = ClientFactory.GetClient(Cluster.MainNet, httpClient:client);
```

am i doing it wrong?
