### ISSUE TITLE
Support for smart contracts

### ISSUE THREAD

**Issue by Liebeck** [bmresearch/Solnet#247]
As far as I understand, smart contracts for Solana are written in Rust, C or C++ and then compiled into Solana BPF Bytecode.

Is there anything planned for Solnet in terms of smart contract support? So far I've only used Solnet as JSON RPC API wrapper to interact with the nodes. It would be great to be able to use C# for smart contracts, similar to NEO.

**Comment by Neo-vortex** [comment]
`Transpile into Rust and call the current Solana toolchain.` sounds counter-intuitive too.
Probably we could make some limited template for popular themes that people use in smart contract (such as splinting some amount among variable/hard-coded public keys), and then let people build up these templates from C#.

We also have some limited NativeAOT with LLVM backend for C# (see [here](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM)  and [here](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT))
but sounds very hard to get anything working considering NativeAOT is still in preview itself!

I am actually thinking about making smart contracts available from C# code base but things are hard to be handled by a single person.I can start working on some  popular themes for smart contracts if you agree with this approach
