### ISSUE TITLE
[Bug] Deserialization GetSpan copies serve no purpose but to create huge memory allocation

### ISSUE THREAD

**Issue by matthewcpollard** [bmresearch/Solnet#261]
**Describe the bug**
In Deserialization.cs
public static Span<byte> GetSpan(this ReadOnlySpan<byte> data, int offset, int length)
    {
      if (offset + length > data.Length)
        throw new ArgumentOutOfRangeException(nameof (offset));
      byte[] numArray = new byte[length];
      data.Slice(offset, length).CopyTo((Span<byte>) numArray);
      return (Span<byte>) numArray;
    }
    
It seems this can be simplified in all paths to just data.Slice(offset,length) (and changing ReadOnlySpan<byte> to just Span<byte>). The copy doesn't serve any purpose. 

In my usage (subscribing to orderbookside updates), I see 150mb of allocation from this method in one minute of the program running.

**Comment by murlokito** [comment]
Hmmm... What code are you using that is using this `GetSpan` method for orderbook sides? Both the Serum and Mango libraries I did are just using slices for orderbook and EQ updates specifically because I wanted to keep them as performant as possible

**Comment by murlokito** [comment]
Looks like this was actually an oversight from my part and those are actually being used. I'll fix this GetSpan but will need to issue a new release of the mango and serum libs as well.

**Comment by matthewcpollard** [comment]
Thanks for the quick reply murlokito.
