### ISSUE TITLE
GetProgramAccounts with update authority MemCmp

### ISSUE THREAD

**Issue by tratteo** [bmresearch/Solnet#263]
### Premise  
Hope this is not due to some error I am making.

---

**Describe the bug**
I am using the RPC call `GetProgramAccounts/Async` on the Token Metadata program ID in order to retrieve all tokens by a certain updateAuthority address. I got to know that the updateAuthority is at offset 1 (is it right?), therefore I am using the following MemCmp:
```c#
filters.Add(new()
{
    Offset = 1,
    Bytes = Encoders.Base58.EncodeData(Encoding.UTF8.GetBytes(updateAuthority))
});
```
however, the call returns no results.
If I do not use the updateAuthority MemCmp and search by something else (for example name <offset 69> or symbol <offset 105>) I am able to retrieve the mint addresses. And, by using:
```c#
var bytes = Convert.FromBase64String(pair.Account.Data[0]);
string updateAuthority = ((ReadOnlySpan<byte>)bytes).GetPubKey(1);
```
I can retrieve the updateAuthority. Thus, I deduced that the Offset for the updateAuthority should be 1.

**To Reproduce**
Call GetProgramAccounts/Async RPC request with the following MemCmp as filter:
```c#
filters.Add(new()
{
    Offset = 1,
    Bytes = Encoders.Base58.EncodeData(Encoding.UTF8.GetBytes(updateAuthority))
});
```

**Expected behavior**
I am expecting to be able to filter by updateAuthority.

**Desktop (please complete the following information):**
 - OS: Windows x64

**Comment by murlokito** [comment]
This looks to me like it is a minor oversight and not a bug, we've been using GetProgramAccounts with filters without any issues.

After a quick look at the metaplex repo and Solnet.Metaplex it looks like the UpdateAuthority is indeed at offset 1 after the Key which defines the type of the account.

Would it be possible for you to initialize the UpdateAuthority as a PublicKey and try the following? 

```
filters.Add(new() { 
Offset = 1, 
Bytes = Encoders.Base58.EncodeData(updateAuthority.KeyBytes) });
```

**Comment by murlokito** [comment]
Or rather, it looks like you're performing conversion string -> bytes -> base58 encoding, this doesn't seem right to me, look at this example from Solnet.Mango where the public key is passed as a string into the method

```        /// <inheritdoc cref="IMangoClient.GetPerpMarketsAsync(string, Commitment)"/>
        public async Task<ProgramAccountsResultWrapper<List<PerpMarket>>> GetPerpMarketsAsync(string mangoGroup,
            Commitment commitment = Commitment.Finalized)
        {
            List<MemCmp> filters = new()
            {
                new MemCmp { Offset = PerpMarket.Layout.MangoGroupOffset, Bytes = mangoGroup }
            };

            return await GetProgramAccounts<PerpMarket>(MangoProgram.ProgramIdKeyV3, filters, PerpMarket.Layout.Length,
                commitment);
        }```

You can probably just do 

```filters.Add(new()
{
    Offset = 1,
    Bytes = updateAuthority
});```

**Comment by tratteo** [comment]
> This looks to me like it is a minor oversight and not a bug, we've been using GetProgramAccounts with filters without any issues.
> 
> After a quick look at the metaplex repo and Solnet.Metaplex it looks like the UpdateAuthority is indeed at offset 1 after the Key which defines the type of the account.
> 
> Would it be possible for you to initialize the UpdateAuthority as a PublicKey and try the following?
> 
> ```cs
> filters.Add(new() { 
>     Offset = 1, 
>     Bytes = Encoders.Base58.EncodeData(updateAuthority.KeyBytes) 
> });
> ```
---
> Or rather, it looks like you're performing conversion string -> bytes -> base58 encoding, this doesn't seem right to me, look at this example from Solnet.Mango where the public key is passed as a string into the method
> 
> ```cs
> /// <inheritdoc cref="IMangoClient.GetPerpMarketsAsync(string, Commitment)"/>
> public async Task<ProgramAccountsResultWrapper<List<PerpMarket>>> GetPerpMarketsAsync(string mangoGroup,
>             Commitment commitment = Commitment.Finalized)
> {
>     List<MemCmp> filters = new()
>     {
>          new MemCmp { Offset = PerpMarket.Layout.MangoGroupOffset, Bytes = mangoGroup }
>     };
> 
>     return await GetProgramAccounts<PerpMarket>(MangoProgram.ProgramIdKeyV3, filters, PerpMarket.Layout.Length,
>                 commitment);
> }
> ```
> 
> You can probably just do
> 
> ```cs
> filters.Add(new()
> {
>     Offset = 1,
>     Bytes = updateAuthority
> });
> ```
---
I tried both methods and indeed they both works. I didn't know about the `KeyBytes` field of the `PublicKey` class. I guess the class must have an implicit operator such that:
```c#
public static implicit operator string(PublicKey key) => key.KeyBytes
```

**Comment by murlokito** [comment]
Indeed, we have added operators on `PublicKey` so that operating with `byte[]` and `string` is much easier in a number of different places. Are you able to get the tokens by the authority now?

**Comment by tratteo** [comment]
Yes I am able to filter by update authority now, thanks for the fast responses.
Since I am here, may I ask which way would be the fastest in order to retrieve the owner address (of an NFT, token with supply 1) having the mint address? Currently using: `GetLargestAccount -> >GetAccountInfo`

**Comment by murlokito** [comment]
That does seem like the fastest way, yes, although I've never actually had to do it like that.

I don't know if you've ever seen [this](https://github.com/MonkeDAO/observer/), it was a watcher I did for nft marketplaces some time ago just for fun. In this context what I had to do was figure out who was buying/selling/delisting only having the transactions in which the sale occurred and had to figure it out from the destination token account, the following links might help if you ever need something like that.

https://github.com/MonkeDAO/observer/blob/master/Observer/Handlers/DigitalEyesHandler.cs#L31-L35
https://github.com/MonkeDAO/observer/blob/master/Observer/MetaplexHelpers.cs#L44-L64

**Comment by tratteo** [comment]
Thank you very much for the information it was very helpful. Really appreciate it.
I think this issue may be closed then 😃

**Comment by murlokito** [comment]
In the future if you need any help but are unsure if it's a bug feel free to open a [discussion](https://github.com/bmresearch/Solnet/discussions) :)
