### ISSUE TITLE
[Bug] Can't use Rpc Endpoint likes https://my-api/token/

### ISSUE THREAD

**Issue by nazbrok** [bmresearch/Solnet#270]
**Describe the bug**
Quicknode use a Token in the URL following this format https://my-api/token/ (see here [https://www.quicknode.com/docs/solana](https://www.quicknode.com/docs/solana) )

Actually, when we use Solnet with this baseUrl, all the request sent return with a "Unauthorized" error.

in the JsonRpcClient class a request is created like this

https://github.com/bmresearch/Solnet/blob/f5b97d86b55d1bb9eecc19cc3a08e3cb5f5fb7c1/src/Solnet.Rpc/Core/Http/JsonRpcClient.cs#L76

the last parameter "/" actually seems to remove the token part in the url so the Rpc client cannot authorize the request.
if you change it to "" the request is correctly Authorized.

**To Reproduce**

**Expected behavior**
Be able to use a RPC url containing an authentication token

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MAC OS 

**Additional context**

**Comment by ymrah** [comment]
Hey man,

I use quicknode and this works for me:

IRpcClient rpcClient = ClientFactory.GetClient("https://my-api/token")));

**Comment by tiago18c** [comment]
@nazbrok can you confirm if @ymrah's suggestion worked?

**Comment by nazbrok** [comment]
This is how I am using it but I will do some tests next week.

**Comment by nazbrok** [comment]
I confirm it is not working.

below a simple test using the TOKEN api with the current code

<img width="1059" alt="Capture d’écran 2021-12-20 à 10 56 59" src="https://user-images.githubusercontent.com/1686551/146751749-cdba23ed-aefd-42df-a123-1e4900c6ac82.png">


below  is the same request but without the requestUri parameter in the HttpRequestMessage
<img width="1074" alt="Capture d’écran 2021-12-20 à 11 01 21" src="https://user-images.githubusercontent.com/1686551/146751392-45150597-7104-4a50-ae15-9e248a43b5e5.png">



I will submit a PR.

**Comment by murlokito** [comment]
Closed by #271
