### ISSUE TITLE
[Bug] Example Code dose not compile 

### ISSUE THREAD

**Issue by Neo-vortex** [bmresearch/Solnet#277]
**Describe the bug**
in the examples :
`            var minBalanceForExemptionAcc = rpcClient.GetMinimumBalanceForRentExemption(SystemProgram.AccountDataSize).Result;`

`SystemProgram.AccountDataSize` is not found 

**To Reproduce**
copy and past the example code of minting and try to compile 

**Expected behavior**
code should compile 

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 0.4.16

**Comment by murlokito** [comment]
This is related to #267, in this concrete example it should be `TokenProgram.TokenAccountDataSize`

**Comment by murlokito** [comment]
Closed by #280
