### ISSUE TITLE
[Bug] IRpcClient not work

### ISSUE THREAD

**Issue by Intekai** [bmresearch/Solnet#278]
**Describe the bug**
IRpcClient rpcClient = ClientFactory.GetClient(Cluster.TestNet);

***not work
        var balance = rpcClient.GetBalance(wallet.Account.PublicKey);

**To Reproduce**

  var wallet = new Wallet(WordCount.TwentyFour, WordList.English);

        Console.WriteLine("Hello World!");
        Console.WriteLine($"Mnemonic: {wallet.Mnemonic}");
        Console.WriteLine($"PubKey: {wallet.Account.PublicKey.Key}");
        Console.WriteLine($"PrivateKey: {wallet.Account.PrivateKey.Key}");

        IRpcClient rpcClient = ClientFactory.GetClient(Cluster.TestNet);

*****not work
        var balance = rpcClient.GetBalance(wallet.Account.PublicKey);

**Comment by murlokito** [comment]
Can you be more specific about the error?

**Comment by Intekai** [comment]
I have create new project to vs2022. Net 6.0 and I have copy the code. When I set debuf on line to get a balance the system go to the loop. Inviato dal mio telefono HONOR-------- Messaggio originale --------Da: hoak ***@***.***>Data: lun 27 dic 2021, 19:51A: bmresearch/Solnet ***@***.***>Cc: Intekai ***@***.***>, Author ***@***.***>Oggetto: Re: [bmresearch/Solnet] [Bug] IRpcClient not work (Issue #278)
Can you be more specific about the error?

**Comment by Intekai** [comment]
![image](https://user-images.githubusercontent.com/68114285/147550716-bfc86287-4894-4ba3-9176-8633956f9916.png)
view this image when i debug this line the system go to loop

**Comment by tiago18c** [comment]
With Blazor you need to use the *Async functions, the non-asyncs won't work.

```
var balance = await rpcClient.GetBalanceAsync(wallet.Account.PublicKey);
```
