### ISSUE TITLE
[Bug] SystemProgram.AccountDataSize  not found

### ISSUE THREAD

**Issue by Intekai** [bmresearch/Solnet#279]
**Describe the bug**
var blockHash = rpcClient.GetRecentBlockHash();
var minBalanceForExemptionAcc =
    rpcClient.GetMinimumBalanceForRentExemption(**_SystemProgram.AccountDataSize_**).Result;

.AccountDataSize_  not found...

**Comment by murlokito** [comment]
This is related to #267 and #277, in this concrete example it should be `TokenProgram.TokenAccountDataSize`

**Comment by murlokito** [comment]
Closed by #280
