### ISSUE TITLE
Full JSON RPC API coverage

### ISSUE THREAD

**Issue by murlokito** [bmresearch/Solnet#31]
Provide an implementation for each of the following HTTP JSON RPC API methods:

- [X] getAccountInfo
- [X] getBalance
- [x] getBlock
- [X] getBlockHeight
- [x] getBlockProduction
- [X] getBlockCommitment
- [x] getBlocks
- [x] getBlocksWithLimit
- [X] getBlockTime
- [X] getClusterNodes
- [x] getEpochInfo
- [x] getEpochSchedule
- [x] getFeeCalculatorForBlockhash
- [x] getFeeRateGovernor
- [x] getFees
- [x] getFirstAvailableBlock
- [X] getGenesisHash
- [x] getHealth
- [X] getIdentity
- [X] getInflationGovernor
- [X] getInflationRate
- [X] getInflationReward
- [X] getLargestAccounts
- [x] getLeaderSchedule
- [x] getMaxRetransmitSlot
- [x] getMaxShredInsertSlot
- [X] getMinimumBalanceForRentExemption
- [x] getMultipleAccounts
- [x] getProgramAccounts
- [X] getRecentBlockhash
- [x] getRecentPerformanceSamples
- [x] getSignaturesForAddress
- [x] getSignatureStatuses
- [x] getSlot
- [x] getSlotLeader
- [x] getSlotLeaders
- [x] getStakeActivation
- [X] getSupply
- [X] getTokenAccountBalance
- [X] getTokenAccountsByDelegate
- [X] getTokenAccountsByOwner
- [X] getTokenLargestAccounts
- [X] getTokenSupply
- [x] getTransaction
- [X] getTransactionCount
- [x] getVersion
- [x] getVoteAccounts
- [X] minimumLedgerSlot
- [X] requestAirdrop
- [X] sendTransaction
- [X] simulateTransaction

Provide an implementation for each of the following WS JSON RPC API methods:

- [X] accountSubscribe
- [X] accountUnsubscribe
- [X] logsSubscribe
- [X] logsUnsubscribe
- [X] programSubscribe
- [X] programUnsubscribe
- [X] signatureSubscribe
- [X] signatureUnsubscribe
- [X] slotSubscribe
- [X] slotUnsubscribe

Mark them as done as we go, once all are done, close the issue and move on, cool guys don't look at explosions.

**Comment by tiago18c** [comment]
Done :)
