### ISSUE TITLE
CreateWithSeed for PublicKey class

### ISSUE THREAD

**Issue by Neo-vortex** [bmresearch/Solnet#326]
**Is your feature request related to a problem? Please describe.**
Sometimes we need derive the address of a account for a specific program.
I am not aware of any API in Solnet to achieve this.

**Describe the solution you'd like**
Probably `PublicKey` should have a static method named `createWithSeed` for ease.

**Additional context**
here is the js counterpart API :
```ts
  const GREETING_SEED = 'hello';
  greetedPubkey = await PublicKey.createWithSeed(
    payer.publicKey,
    GREETING_SEED,
    programId,
  );
```
source : https://github.com/solana-labs/example-helloworld/blob/d7b852dd94be16572dfe2bf8e088040e5a191534/src/client/hello_world.ts#L164

**Comment by murlokito** [comment]
We have several methods in Solnet which facilitate derivation of PDAs, you should check [this](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Rpc/Utilities/AddressExtensions.cs) and maybe [this `TryCreateWithSeed`](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Programs/Utilities/Serialization.cs#L258) which is used in the context of the Stake Program... I'm unsure which one best fits your needs. The first link is used extensively in Solnet.Serum and Solnet.Mango to derive vault signer PDAs, mango accounts, advanced orders accounts etc

**Comment by Neo-vortex** [comment]
Thanks!
[this](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Programs/Utilities/Serialization.cs#L258)
did the trick!
