### ISSUE TITLE
Token-Swap program example doesn't work[Bug]

### ISSUE THREAD

**Issue by AliAhmadi99** [bmresearch/Solnet#348]
I've tried to run the project examples. all of them are fine but I get errors when in TokenSwapExample. I'll attach the logs

![image](https://user-images.githubusercontent.com/51044940/156738298-cbb1c599-bf08-4ae5-b207-0e1c069b0a16.png)

**Comment by KeithWalton** [comment]
I get this error in the console when trying to run the token swap example:
      Sending request: {"method":"getTransaction","params":[{"encoding":"json"}],"jsonrpc":"2.0","id":5}
16:01:47 info: Solnet.Rpc.IRpcClient[5]
      Result: {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid type: map, expected a string."},"id":5}

**Comment by AliAhmadi99** [comment]
My suggestion: go and learn rust to become a Solana developer. the other communities are very very small and unsupportive

**Comment by Neo-vortex** [comment]
> My suggestion: go and learn rust to become a Solana developer. the other communities are very very small and unsupportive 

Yeh!
And then try to build android apps, web apps, desktop apps and everything with rust!!

This library is mostly for consuming solana api, nothing special.

**Comment by AliAhmadi99** [comment]
I took a look at your profile and it was interesting for me. may I dm u on LinkedIn if you don't mind
