### ISSUE TITLE
Pushing smart contract to solana

### ISSUE THREAD

**Issue by Neo-vortex** [bmresearch/Solnet#361]
Imagine a compiled smart contract is in hand. (compiled with cargo  build-bpf)
how to push it to solana network using solnet  ?

**Comment by murlokito** [comment]
I don't think it makes much sense to push it using Solnet considering the solana-cli already has the tools to do this.. Anyway, it doesn't seem like we have the Upload/Upgrade instructions from the [BPF Loader](https://docs.solana.com/developing/runtime-facilities/programs#bpf-loader) implemented which you'd need to upload the compiled program binaries into the network.

**Comment by Neo-vortex** [comment]
Actually it is much needed as we are developing a Block-chain based store to manage smart contracts.
I will try to implement it and open a PR
