### ISSUE TITLE
How to sign/verify a message

### ISSUE THREAD

**Issue by stefannovak** [bmresearch/Solnet#375]
Hey, this isn't a bug issue. I've been trying to use this package to sign and verify a message. I want to recover a Sol address from a signed message and a verified message. Is this possible? Thanks

**Comment by murlokito** [comment]
[Here](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Wallet/Account.cs#L54-L67) you have methods which allow to sign and verify a message. The way you would go about to recover the sol address would be done around these methods.

**Comment by stefannovak** [comment]
> [Here](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Wallet/Account.cs#L54-L67) you have methods which allow to sign and verify a message. The way you would go about to recover the sol address would be done around these methods.

Thank you very much!
