### ISSUE TITLE
Sending an SPL token Example doesn't work

### ISSUE THREAD

**Issue by n0n3mi1y** [bmresearch/Solnet#376]
I tried using an example of sending a token. However, I got an error saying that 4 arguments are needed. How do I create a fourth argument?

My code:
`static void TestSendingUSDC()
        {
           
            var wallet1 = new Solnet.Wallet.Wallet("pudding border fetch text reward text cat jacket fetch cat correct amount");

            var client = ClientFactory.GetClient(Cluster.MainNet);
            var tokens = new TokenMintResolver();
            var wallet = TokenWallet.Load(client, tokens, wallet1.Account.PublicKey);

          
            var source = wallet.TokenAccounts().ForToken(WellKnownTokens.USDC).FirstOrDefault();
            

            
            var sig = wallet.Send(source, (decimal)1.0D, "332DjJ3TSuZeafhYPsnN8xaNDiBF6Q2oxcCKsWtQRPN5", wallet1.Account.PublicKey);
            //wallet.Send(sig);
            
        }`

**Comment by murlokito** [comment]
[TokenWallet.Send](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Extensions/TokenWallet.cs#L307) requires 5 arguments, the 5th argument is a callback.

It appears you're missing the callback that is used to sign the tx.

```
var sig = wallet.Send(source, (decimal)1.0D, "332DjJ3TSuZeafhYPsnN8xaNDiBF6Q2oxcCKsWtQRPN5", wallet1.Account.PublicKey, (txbuilder) => 
{
    return txbuilder.Build(wallet1);
});
```

**Comment by n0n3mi1y** [comment]
well, i tried ur code.
I got an error of convert from Solnet.Wallet.Wallet to Solnet.Wallet.Account

I replaced return txbuilder.Build(wallet1); to return txbuilder.Build(wallet1.Account);
Then I got a error: One or more errors occurred. (DecimalPlaces is unknown for mint EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v)"

Does it mean that i can't transfer this token with decimal? Or what?

**Comment by n0n3mi1y** [comment]
Yeah, i replaced TokenInfoResolver() to TokenMintResolver because i got a error too.

**Comment by n0n3mi1y** [comment]
Maybe I missed some using directive?

**Comment by murlokito** [comment]
There is no need for a using directive, it looks like for some reason it couldn't find the decimals for USDC - let me take a look.

**Comment by murlokito** [comment]
You are merely initializing a `TokenMintResolver` but you are not loading any tokens (this should be changed to mitigate these kinds of mishaps)

Change

```
var tokens = new TokenMintResolver();
```

to

```
var tokens = TokenMintResolver.Load(); // or await TokenMintResolver.LoadAsync(); in case you need this to be async
```

**Comment by n0n3mi1y** [comment]
Thanks! It worked!
But now i got this error:
![image](https://user-images.githubusercontent.com/89714119/166151817-f233ea5f-e492-422f-a219-832773e1c7a7.png)
Can I change any parameters to fix this?

**Comment by n0n3mi1y** [comment]
The issue is removed, more SOL was needed. Thank U again!!
Please, update instructions if U can.

**Comment by murlokito** [comment]
We have a bunch of things to update all around, I'll add this to the list :)

**Comment by liquizard** [comment]
I'll pick up this + add to #368 update the example in the readme.
