### ISSUE TITLE
[Bug]Does't work well on unity.

### ISSUE THREAD

**Issue by devzhuchuanbo** [bmresearch/Solnet#408]
**Describe the bug**
I tried to import all the dll files to my unity project, I can write some code to invoke most of the functions, but it does't work when I play or build it.

**To Reproduce**
1. inport all the released dll files to unity Plugins folder
2. write some sample code
3. play or build

**Screenshots**
![Snipaste_2022-07-26_15-45-59](https://user-images.githubusercontent.com/20489157/180952873-875519c5-a1fc-4c5c-b8e1-b1a1e8f63660.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Unity version [2020.3.24]

**Comment by GabrielePicco** [comment]
@devzhuchuanbo see related issue here #383 . We ported this amazing library for Unity and we will try to keep it on track with the latest version. You can find it here: https://github.com/garbles-labs/Solana.Unity-Core
