### ISSUE TITLE
Two new features request

### ISSUE THREAD

**Issue by Joter271** [bmresearch/Solnet#445]
We require two new features and help with integration of updated code.
First feature is integration of version transactions (https://github.com/bmresearch/Solnet/issues/360)
Second feature is implementation of high priority fees (https://solana.com/developers/guides/advanced/how-to-use-priority-fees)

I have created job offering on Upwork. If anyone is interested in adding two new feature for pay.
https://www.upwork.com/jobs/~017f60fcc84ecdc5f7

**Comment by PawelTroka** [comment]
@Joter271 you can contact me on any of my social links
