### ISSUE TITLE
[Bug] ComputeBudgetProgram Usage

### ISSUE THREAD

**Issue by Axlii50** [bmresearch/Solnet#456]
Hi, im trying to use ComputeBudgetProgram
however when trying to use  it i get error 
![image](https://github.com/bmresearch/Solnet/assets/34549741/3e1cd86b-9b40-4400-93d7-07f54456a7dc)
that such namespace doesnt exist 
but in this link 
https://github.com/bmresearch/Solnet/blob/5fbb059997ba1a2cc61f31f2936b16d7325b5b72/src/Solnet.Programs/ComputeBudgetProgram.cs
and when repo is downloaded 
![image](https://github.com/bmresearch/Solnet/assets/34549741/f31eeabd-933b-4db2-9826-e163149015a5)
every thinks looks fine 
but still cant use this program

ive temporarly copied just source code so i can use this methods 
![Uploading image.png…]()

however such solution is not the best

**Comment by tymur999** [comment]
Having the same issue.

**Comment by Axlii50** [comment]
@b0l0k @nazbrok @tiago18c

**Comment by BifrostTitan** [comment]
The latest version of solnet can be found under the net8 solana tags on nuget

https://www.nuget.org/packages/Solana.Rpc
