### ISSUE TITLE
[Bug] Owner property from TokenBalanceInfo is missing from GetTransactionAsync

### ISSUE THREAD

**Issue by marcusruas** [bmresearch/Solnet#458]
**Describe the bug**
The GetTransactionAsync method returns an object of type TransactionMetaSlotInfo, and in the property Meta.PreTokenBalances, if we look at the class TokenBalanceInfo, it doesnt have the Owner property that the Solana API returns. I did some digging and I can see a PR was submitted to implement this property 2 years ago (https://github.com/bmresearch/Solnet/pull/406), but in the current versions, this property is just not there... 

**To Reproduce**

Execute the GetTransactionAsync (or the syncronous version);
Check for the first item of the PostTokenBalances array;
You can see that it's missing

**Screenshots**
The decompiled version:
![image](https://github.com/bmresearch/Solnet/assets/43018213/d9256caf-0bba-40a4-a2c1-e934e824b77e)

**Comment by BifrostTitan** [comment]
The latest version of solnet can be found under the net8 solana tags on nuget

https://www.nuget.org/packages/Solana.Rpc
