### ISSUE TITLE
[Bug] TokenBalanceInfo Missing Owner field

### ISSUE THREAD

**Issue by miaobei5555** [bmresearch/Solnet#460]
**Describe the bug**
TokenBalanceInfo Missing Owner field 
Can you add this field

**Comment by BifrostTitan** [comment]
Owner property in the TokenBalanceInfo class already exists. 
TransactionMeta class contains TokenBalanceInfo arrays called PreTokenBalances and PostTokenBalances. When observing block info you should be able to derive the TransactionMeta from TransactionMetaInfo array named Transactions in the blockinfo class.

https://github.com/bmresearch/Solnet/blob/5fbb059997ba1a2cc61f31f2936b16d7325b5b72/src/Solnet.Rpc/Models/Block.cs#L275C1-L275C42
