### ISSUE TITLE
Can we publish a new Nuget version?

### ISSUE THREAD

**Issue by NightWuYo** [bmresearch/Solnet#471]
The latest version 6.1.0 was published more than two years ago, there have been many changes since then, a new version would make people's life easier.

**Comment by BifrostTitan** [comment]
## Latest Nuget Packages
- [Solnet.Rpc](https://www.nuget.org/packages/Solana.Rpc/)
- [Solnet.Wallet](https://www.nuget.org/packages/Solana.Wallet/)
- [Solnet.Programs](https://www.nuget.org/packages/Solana.Programs/)
- [Solnet.Extensions](https://www.nuget.org/packages/Solana.Extensions/)
- [Solnet.Keystore](https://www.nuget.org/packages/Solana.Keystore/)

Latest nuget package links are in the readme. search net8 & solnet to find all the latest packages on nuget easily
https://github.com/bmresearch/Solnet?tab=readme-ov-file#latest-nuget-packages
